# Generated by Django 4.1.7 on 2023-04-04 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_alter_blog_posted_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 4, 11, 8, 54, 281788), verbose_name='Опубликована'),
        ),
    ]
