# Generated by Django 4.1.7 on 2023-04-11 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_blog_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст коммнетария')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 11, 16, 13, 3, 531897), verbose_name='Дата добавления комментария')),
                ('author', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('post', models.CharField(max_length=1000, verbose_name='Статья для комментария')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 11, 16, 13, 3, 529904), verbose_name='Опубликована'),
        ),
    ]
