# Generated by Django 4.1.7 on 2023-04-12 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_blog_posted_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Комментарии к статье блога', 'verbose_name_plural': 'Комментарии к статьям блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 12, 16, 42, 5, 210594), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 12, 16, 42, 5, 211576), verbose_name='Дата добавления комментария'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
